"""news_likes_comments

Revision ID: 89937d21df2d
Revises: be93df809a4b
Create Date: 2026-04-10 18:51:39.662001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89937d21df2d'
down_revision: Union[str, None] = 'be93df809a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_comments_news_id'), 'news_comments', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_comments_user_id'), 'news_comments', ['user_id'], unique=False)
    op.create_table('news_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'news_id', name='uq_news_like')
    )
    op.create_index(op.f('ix_news_likes_news_id'), 'news_likes', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_likes_user_id'), 'news_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_likes_user_id'), table_name='news_likes')
    op.drop_index(op.f('ix_news_likes_news_id'), table_name='news_likes')
    op.drop_table('news_likes')
    op.drop_index(op.f('ix_news_comments_user_id'), table_name='news_comments')
    op.drop_index(op.f('ix_news_comments_news_id'), table_name='news_comments')
    op.drop_table('news_comments')
    # ### end Alembic commands ###
