"""banner_body_ustuni

Revision ID: fb91199c9352
Revises: e4a05f7dd8c4
Create Date: 2026-04-09 22:55:18.245550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb91199c9352'
down_revision: Union[str, None] = 'e4a05f7dd8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('body', sa.Text(), nullable=True))
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_column('banners', 'body')
    # ### end Alembic commands ###
